// file: seeds/10_assets.js
exports.seed = async function (knex) {
  await knex("assets").del();
  await knex("assets").insert([
    {
      id: "1",
      guiId: "GUI001",
      user_id: "1",
      contract_id: "1",
      product_category_id: "1",
      product_sub_category_id: "1",
      company_id: "1",
      asset_site_id: "1",
      service_id: "1",
      notes_id: "1",
      asset_type: "Hardware",
      asset_name: "Asset A",
      serial_number: "SN001",
      supported: true,
      status: "New",
      priority: "High",
      attach_image: "asset1.jpg",
      description: "Asset A Description",
      isDeleted: false,
    },
    {
      id: "2",
      guiId: "GUI002",
      user_id: "2",
      contract_id: "2",
      product_category_id: "2",
      product_sub_category_id: "2",
      company_id: "2",
      asset_site_id: "2",
      service_id: "2",
      notes_id: "2",
      asset_type: "Software",
      asset_name: "Asset B",
      serial_number: "SN002",
      supported: true,
      status: "Deployed",
      priority: "Medium",
      attach_image: "asset2.jpg",
      description: "Asset B Description",
      isDeleted: false,
    },
    {
      id: "3",
      guiId: "GUI003",
      user_id: "3",
      contract_id: "3",
      product_category_id: "3",
      product_sub_category_id: "3",
      company_id: "3",
      asset_site_id: "3",
      service_id: "3",
      notes_id: "3",
      asset_type: "Hardware",
      asset_name: "Asset C",
      serial_number: "SN003",
      supported: false,
      status: "In Inventory",
      priority: "Low",
      attach_image: "asset3.jpg",
      description: "Asset C Description",
      isDeleted: false,
    },
  ]);
};
